### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by ovr** [fsvh/eTorrent#1]
Hi
Any news on this project? How can I help to develop this project?
:smile_cat:

**Comment by ghost** [comment]
the project progresses : https://github.com/inizan-yannick/transfert

I'll get back to it when I have time ;)

**Comment by guilmour-asc** [comment]
I don't know if anyone will see it, but the dream has become [true](https://github.com/davidmhewitt/torrential)...

**Comment by ovr** [comment]
~ 4 years. lol
